name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: respondruk_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PostgreSQL
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d respondruk_test -f scripts/db_setup.sql

    - name: Run Database Tests
      run: |
        # Add database tests here
        echo "Database tests to be implemented"
